### ISSUE TITLE
Je hebt nog geen live linkje

### ISSUE THREAD

**Issue by KrijnHoetmer** [SjorsPk/Visitekaartje-Nieuw#1]
Kijk nog even naar de stappen voor Integreren uit [de instructies van maandag](https://github.com/fdnd-task/your-tribe-profile-card/blob/main/docs/visitekaartje-ontwerpen-maken-en-online-publiceren.md#2-online-publiceren).

**Comment by SjorsPk** [comment]
Het is gefixt!
